// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournoiAPI.Data;

#nullable disable

namespace TournoiAPI.Migrations
{
    [DbContext(typeof(TournoiDbContext))]
    partial class TournoiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournoiAPI.Models.Classement", b =>
                {
                    b.Property<int>("ID_Classement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Classement"));

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Equipe")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tournoi")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("ID_Classement");

                    b.HasIndex("ID_Equipe");

                    b.HasIndex("ID_Tournoi");

                    b.ToTable("Classements");
                });

            modelBuilder.Entity("TournoiAPI.Models.Equipe", b =>
                {
                    b.Property<int>("ID_Equipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Equipe"));

                    b.Property<string>("Capitaine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NombreJoueurs")
                        .HasColumnType("int");

                    b.HasKey("ID_Equipe");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("TournoiAPI.Models.EquipeTournoi", b =>
                {
                    b.Property<int>("ID_EquipeTournoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_EquipeTournoi"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Equipe")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tournoi")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_EquipeTournoi");

                    b.HasIndex("ID_Equipe");

                    b.HasIndex("ID_Tournoi");

                    b.ToTable("EquipesTournois");
                });

            modelBuilder.Entity("TournoiAPI.Models.Match", b =>
                {
                    b.Property<int>("ID_Match")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Match"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Equipe1")
                        .HasColumnType("int");

                    b.Property<int>("ID_Equipe2")
                        .HasColumnType("int");

                    b.Property<int>("ID_Tournoi")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreEquipe1")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreEquipe2")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Match");

                    b.HasIndex("ID_Equipe1");

                    b.HasIndex("ID_Equipe2");

                    b.HasIndex("ID_Tournoi");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TournoiAPI.Models.Tournoi", b =>
                {
                    b.Property<int>("ID_Tournoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tournoi"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("NbEquipesMax")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reglement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Tournoi");

                    b.ToTable("Tournois");
                });

            modelBuilder.Entity("TournoiAPI.Models.Classement", b =>
                {
                    b.HasOne("TournoiAPI.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("ID_Equipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournoiAPI.Models.Tournoi", "Tournoi")
                        .WithMany("Classements")
                        .HasForeignKey("ID_Tournoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("TournoiAPI.Models.EquipeTournoi", b =>
                {
                    b.HasOne("TournoiAPI.Models.Equipe", "Equipe")
                        .WithMany("EquipesTournois")
                        .HasForeignKey("ID_Equipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournoiAPI.Models.Tournoi", "Tournoi")
                        .WithMany("EquipesTournois")
                        .HasForeignKey("ID_Tournoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("TournoiAPI.Models.Match", b =>
                {
                    b.HasOne("TournoiAPI.Models.Equipe", "Equipe1")
                        .WithMany("MatchesEquipe1")
                        .HasForeignKey("ID_Equipe1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournoiAPI.Models.Equipe", "Equipe2")
                        .WithMany("MatchesEquipe2")
                        .HasForeignKey("ID_Equipe2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournoiAPI.Models.Tournoi", "Tournoi")
                        .WithMany("Matches")
                        .HasForeignKey("ID_Tournoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe1");

                    b.Navigation("Equipe2");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("TournoiAPI.Models.Equipe", b =>
                {
                    b.Navigation("EquipesTournois");

                    b.Navigation("MatchesEquipe1");

                    b.Navigation("MatchesEquipe2");
                });

            modelBuilder.Entity("TournoiAPI.Models.Tournoi", b =>
                {
                    b.Navigation("Classements");

                    b.Navigation("EquipesTournois");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
